name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show current directory and list files
      run: |
        echo "当前工作目录："
        pwd
        echo "列出项目目录下的所有文件："
        dir "${{ github.workspace }}" /s

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Bootcampforgitrunner.csproj

    - name: Build
      run: dotnet build Bootcampforgitrunner.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test Bootcampforgitrunner.csproj --no-build --verbosity normal